# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: "voiceyourplace-3"

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: "G-ZE2YNMXGGQ"

ro-menu:
  - { name: "Curtea de Argeș", url: "ro/biserica-domneasca" }
  - { name: "Audio ghid", url: "ro/audio-guide" }
  - { name: "Comunitate", url: "ro/community" }
  - { name: "Proiect", url: "ro/project" }
  - { name: "Contact", url: "ro/contact" }
  - { name: "EN", url: "en" }

ro-menu-slatina:
  - { name: "Slatina", url: "ro/biserica-sfanta-treime" }
  - { name: "Audio ghid", url: "ro/audio-guide-slatina" }
  - { name: "Comunitate", url: "ro/community-slatina" }
  - { name: "Proiect", url: "ro/project-slatina" }
  - { name: "Contact", url: "ro/contact" }

en-menu:
  - { name: "Curtea de Argeș", url: "en/biserica-domneasca" }
  - { name: "Audio guide", url: "en/audio-guide" }
  - { name: "Community", url: "en/community" }
  - { name: "Project", url: "en/project" }
  - { name: "Contact", url: "en/contact" }
  - { name: "RO", url: "" }

en-menu-slatina:
  - { name: "Slatina", url: "en/biserica-sfanta-treime" }
  - { name: "Audio guide", url: "en/audio-guide-slatina" }
  - { name: "Project", url: "en/project-slatina" }
  - { name: "Contact", url: "en/contact" }

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
  - {
      icon: "instagram",
      link: "https://instagram.com/voiceyourplace",
      title: "INSTAGRAM",
      image: "logo-instagram.png",
      alt: "Instagram",
    }
  - {
      icon: "facebook",
      link: "https://facebook.com/voiceyourplace",
      title: "FACEBOOK",
      image: "logo-facebook.png",
      alt: "Facebook",
    }
  - {
      icon: "soundcloud",
      link: "https://soundcloud.com/voice-your-place",
      title: "SOUNDCLOUD",
      image: "logo-soundcloud.png",
      alt: "Soundcloud",
    }
  - {
      icon: "youtube",
      link: "https://www.youtube.com/@VoiceYourPlace",
      title: "YOUTUBE",
      image: "logo-youtube.png",
      alt: "Youtube",
    }

social-partners:
  - {
      name: "Partners & Sponsors",
      image: "partners-sponsors.png",
      alt: "Parteneri si sponsori",
    }

social-partners-slatina:
  - {
      name: "Partners & Sponsors",
      image: "partners-sponsors-slatina.png",
      alt: "Parteneri si sponsori",
    }

en-social-partners:
  - {
      name: "Partners & Sponsors",
      image: "en-partners-sponsors.png",
      alt: "Partners & Sponsors",
    }

en-social-partners-slatina:
  - {
      name: "Partners & Sponsors",
      image: "en-partners-sponsors-slatina.png",
      alt: "Partners & Sponsors",
    }

en-community:
  - {
      front: "en-comunitate-front-1.jpg",
      back: "en-comunitate-back-1.jpg",
      url: "/en/community/last-time-forever",
    }
  - {
      front: "en-comunitate-front-2.jpg",
      back: "en-comunitate-back-2.jpg",
      url: "/en/community/the-girl-who-left",
    }
  - {
      front: "en-comunitate-front-3.jpg",
      back: "en-comunitate-back-3.jpg",
      url: "/en/community/capture-fortress",
    }
  - {
      front: "en-comunitate-front-4.jpg",
      back: "en-comunitate-back-4.jpg",
      url: "/en/community/old-hag",
    }
  - {
      front: "en-comunitate-front-5.jpg",
      back: "en-comunitate-back-5.jpg",
      url: "/en/community/parents",
    }
  - {
      front: "en-comunitate-front-6.jpg",
      back: "en-comunitate-back-6.jpg",
      url: "/en/community/posada",
    }
  - {
      front: "en-comunitate-front-7.jpg",
      back: "en-comunitate-back-7.jpg",
      url: "/en/community/reconciliation-olari-church",
    }
  - {
      front: "en-comunitate-front-8.jpg",
      back: "en-comunitate-back-8.jpg",
      url: "/en/community/silence",
    }
  - {
      front: "en-comunitate-front-9.jpg",
      back: "en-comunitate-back-9.jpg",
      url: "/en/community/cristian",
    }
  - {
      front: "en-comunitate-front-10.jpg",
      back: "en-comunitate-back-10.jpg",
      url: "/en/community/broken-doll",
    }
  - {
      front: "en-comunitate-front-11.jpg",
      back: "en-comunitate-back-11.jpg",
      url: "/en/community/do-not-touch-the-exhibits",
    }
  - {
      front: "en-comunitate-front-12.jpg",
      back: "en-comunitate-back-12.jpg",
      url: "/en/community/tic-tac",
    }
  - {
      front: "en-comunitate-front-13.jpg",
      back: "en-comunitate-back-13.jpg",
      url: "/en/community/a-new-beginning",
    }

ro-community:
  - {
      front: "ro-comunitate-front-1.jpg",
      back: "ro-comunitate-back-1.jpg",
      url: "/ro/comunitate/ultima-data-pentru-totdeauna",
    }
  - {
      front: "ro-comunitate-front-2.jpg",
      back: "ro-comunitate-back-2.jpg",
      url: "/ro/comunitate/fata-care-a-plecat",
    }
  - {
      front: "ro-comunitate-front-3.jpg",
      back: "ro-comunitate-back-3.jpg",
      url: "/ro/comunitate/capturarea-cetatii",
    }
  - {
      front: "ro-comunitate-front-4.jpg",
      back: "ro-comunitate-back-4.jpg",
      url: "/ro/comunitate/batrana-hotomana",
    }
  - {
      front: "ro-comunitate-front-5.jpg",
      back: "ro-comunitate-back-5.jpg",
      url: "/ro/comunitate/parintii",
    }
  - {
      front: "ro-comunitate-front-6.jpg",
      back: "ro-comunitate-back-6.jpg",
      url: "/ro/comunitate/leat-6838",
    }
  - {
      front: "ro-comunitate-front-7.jpg",
      back: "ro-comunitate-back-7.jpg",
      url: "/ro/comunitate/impacarea-de-la-biserica-olari",
    }
  - {
      front: "ro-comunitate-front-8.jpg",
      back: "ro-comunitate-back-8.jpg",
      url: "/ro/comunitate/liniste",
    }
  - {
      front: "ro-comunitate-front-9.jpg",
      back: "ro-comunitate-back-9.jpg",
      url: "/ro/comunitate/cristian",
    }
  - {
      front: "ro-comunitate-front-10.jpg",
      back: "ro-comunitate-back-10.jpg",
      url: "/ro/comunitate/cu-dor",
    }
  - {
      front: "ro-comunitate-front-11.jpg",
      back: "ro-comunitate-back-11.jpg",
      url: "/ro/comunitate/nu-atingeti-exponatele",
    }
  - {
      front: "ro-comunitate-front-12.jpg",
      back: "ro-comunitate-back-12.jpg",
      url: "/ro/comunitate/tic-tac",
    }
  - {
      front: "ro-comunitate-front-13.jpg",
      back: "ro-comunitate-back-13.jpg",
      url: "/ro/comunitate/un-nou-inceput",
    }

community-stories:
  - {
      location: "RuinaBisericaSanNicoara",
      title: "Fata care a plecat",
      author: "Ruxandra Radu",
      url: "/ro/comunitate/fata-care-a-plecat",
    }
  - {
      location: "RuinaBisericaSanNicoara",
      title: "Bătrâna hoțomană",
      author: "Ionuț Păduraru",
      url: "/ro/comunitate/batrana-hotomana",
    }
  - {
      location: "RuinaBisericaSanNicoara",
      title: "Capturarea cetății",
      author: "Radu Răducanu",
      url: "/ro/comunitate/capturarea-cetatii",
    }

  - {
      location: "BisericaDomneasca",
      title: "Leat 6838",
      author: "Eduard Băiașu",
      url: "/ro/comunitate/leat-6838",
    }

  - {
      location: "BisericaOlari",
      title: "Liniște",
      author: "Ana Baciu",
      url: "/ro/comunitate/liniste",
    }

  - {
      location: "ManastireaCurteaDeArges",
      title: "Cristian",
      author: "Maria Duca",
      url: "/ro/comunitate/cristian",
    }
  - {
      location: "ManastireaCurteaDeArges",
      title: "Liniște",
      author: "Ana Baciu",
      url: "/ro/comunitate/liniste",
    }

  - {
      location: "CasaNorocea",
      title: "Tic-Tac!",
      author: "Alexia Jianu",
      url: "/ro/comunitate/tic-tac",
    }

  - {
      location: "GaraRegala",
      title: "Fata care a plecat",
      author: "Ruxandra Radu",
      url: "/ro/comunitate/fata-care-a-plecat",
    }

en-community-stories:
  - {
      location: "RuinaBisericaSanNicoara",
      title: "The girl who left",
      author: "Ruxandra Radu",
      url: "/en/community/the-girl-who-left",
    }
  - {
      location: "RuinaBisericaSanNicoara",
      title: "The old hag",
      author: "Ionuț Păduraru",
      url: "/en/community/old-hag",
    }
  - {
      location: "RuinaBisericaSanNicoara",
      title: "The capture of the fortress",
      author: "Radu Răducanu",
      url: "/en/community/capture-fortress",
    }

  - {
      location: "BisericaDomneasca",
      title: "Posada",
      author: "Eduard Băiașu",
      url: "/en/community/posada",
    }

  - {
      location: "BisericaOlari",
      title: "Silence",
      author: "Ana Baciu",
      url: "/en/community/silence",
    }

  - {
      location: "ManastireaCurteaDeArges",
      title: "Cristian",
      author: "Maria Duca",
      url: "/en/community/cristian",
    }
  - {
      location: "ManastireaCurteaDeArges",
      title: "Silence",
      author: "Ana Baciu",
      url: "/en/community/silence",
    }

  - {
      location: "CasaNorocea",
      title: "Tick-Tock!",
      author: "Alexia Jianu",
      url: "/en/community/tic-tac",
    }

  - {
      location: "GaraRegala",
      title: "The girl who left",
      author: "Ruxandra Radu",
      url: "/en/community/the-girl-who-left",
    }

# Customize site text
pagination:
  next_page: "Newer"
  previous_page: "Older"

sharing_button_prompt: "Feel free to share!"

related_posts: "You may also enjoy..."

post_date_prefix: "Written on"
